# Path configuration
paths = {
    'source_directory': '/home/dell/cxx/Steiner-hardness_edited/src/',  # Source code directory
    'data_directory': '/home/dell/cxx/Steiner-hardness_edited/data/'  # Dataset directory
}

# Common configuration
common = {
    'dataset_name': "sift",  # Dataset name
    'KMRNG': 2047,  # KMRNG value
    'postfix': "vecs"  # File suffix, only support 'vecs' now
}

# Preprocessing configuration, {dataset}_query.fvecs is required
preprocess = {
    'efanna_directory': '/home/dell/cxx/efanna_graph/',  # Efanna_graph directory
    'efanna_L': 2400,  # Efanna L value
    'efanna_iter': 10,  # Number of efanna iterations
    'efanna_S': 15,  # Efanna S value
    'efanna_R': 100,  # Efanna R value
    'n_components': 4,  # Number of GMM components
    'n_samples': 50000,  # Number of samples
}

# Hardness calculation configuration
hardness = {
    'k': 50,  # The number of nearest neighbors
    'recall': 0.98,  # Acc, the minimum number of accessed vertices to obtain at least Acc * k vertices in N_k
    'prob': 0.98,  # Probabilistic lower bound to reach the target recall, allowing at least p * k points in N_k are able to reach Acc * k points in N_k
    'groundtruth_dim': 50000,  # Dimension of groundtruth generated by your queries {dataset}_query.fvecs
}

# Benchmark construction configuration
benchmark = {
    'k': 50,  # The number of nearest neighbors
    'recall': 0.98,  # Acc, the minimum number of accessed vertices to obtain at least Acc * k vertices in N_k
    'prob': 0.98,  # Probabilistic lower bound to reach the target recall, allowing at least p * k points in N_k are able to reach Acc * k points in N_k
    'benchmark_query_num': 50000,  # The number of newly generated benchmark queries using GMM generated model in the first phase
    'benchmark_groundtruth_dim': 50000,  # Dimension of benchmark groundtruth generated by benchmark queries
    'workload_size': 10000,  # Workload size
    'n_components': 4,  # Number of GMM components
}
